### ISSUE TITLE
R class

### ISSUE THREAD

**Issue by AllanWang** [jguerinet/MyMartlet#110]
Is your R class import working? After invalidating the project, cleaning, and building, it's still not appearing for me. There exists some problems with newer gradle plugins, though I want to confirm if it's working for you first. Before invalidation pretty much non of the android related imports worked for me.

**Comment by jguerinet** [comment]
I haven't had any problems with the R class import. Are you running the latest versions of everything?

**Comment by AllanWang** [comment]
AS version 3.2.1 (not the newest as of now I believe), but everything else is within the project anyways. I guess I'll try updating that first and see.

**Comment by jguerinet** [comment]
Any news?

**Comment by AllanWang** [comment]
So far it looks like it's working. I still have to build it in the future so I'll see how that goes. Closing this for now

**Comment by AllanWang** [comment]
There's warnings about groupid and version, though we can add that ourselves later

![image](https://user-images.githubusercontent.com/6251823/53048196-34df4e80-3462-11e9-8d52-fcc3426e0af3.png)

**Comment by jguerinet** [comment]
I'm also planning on switching over to Kotlin DSL for Gradle once AS 3.4 comes out.

**Comment by jguerinet** [comment]
Which could help with the above.
