### ISSUE TITLE
[BUG] Cannot login due to bad login detection mechanism

### ISSUE THREAD

**Issue by austinhuang0131** [jguerinet/MyMartlet#116]
This part checks for string "WELCOME" on response:

https://github.com/jguerinet/MyMartlet/blob/31c542a167e1810fff20c943ce36e4039075aaaa/app/src/main/java/util/manager/McGillManager.kt#L135

However, the current Minerva behaviour is that the response of `twbkwbis.P_ValLogin` is *empty* if correct credentials are entered (Incorrect credential does return HTML)

**Comment by jguerinet** [comment]
Hey @austinhuang0131 , thanks for the bug report. 
Unfortunately I do not have time to maintain this project, as much as I want to. This may change in the future, but I don't see it happening until October/November. If you are an Android developer, you are more than welcome to fix the bug and open a PR and I can review it!

**Comment by austinhuang0131** [comment]
I actually do some Android Java (relatively basic though) so I'll try if I have time in the summer

**Comment by jguerinet** [comment]
Please do give it a try! Kotlin is a fantastic language to learn, very easy to jump into. And I'm happy to provide feedback via code reviews!
