### ISSUE TITLE
Notification for Grade Update

### ISSUE THREAD

**Issue by yjzhu1** [jguerinet/MyMartlet#86]
Is there any way you can make a notification sound when Unofficial Transcript is updated? For the winter semester, it was updated daily at [21.30](https://github.com/nicholaspaun/minervaclient/wiki/Minerva-Unofficial-Transcript-Rollover-Times).

**Comment by jguerinet** [comment]
Hey @yjzhu1, that's actually a feature I'm super interested in having as well. Code has been partially written so I need to finish and test, but I'm hoping to have something out before December! See #33  for updates on this, going to close this as a duplicate.
