### ISSUE TITLE
Misc Updates

### ISSUE THREAD

**Issue by AllanWang** [jguerinet/MyMartlet#91]
Hello,

If you'd like some help,  I'm willing to start dedicating some time again for MyMartlet. For the most part, I won't be introducing any major features, but rather cleaning up the app.

Some ideas I have in mind:

* Add back travis. Before, it was mainly for auto generating apks. I'm guessing that won't be necessary anymore, but it may still be worthwhile to have an auto linter for each commit.
* Add spotless. It's a gradle dependency that allows you to use formatters like [ktlint](https://github.com/shyiko/ktlint). It helps you follow coding standards, and will also remove the ugly code diffs that deal with just whitespaces. To add this properly, I'd also be modifying the .idea codestyles just so things like wildcard imports are disabled.
* Misc kotlin fixes. I haven't looked closely at the code yet, but there are things like string formatters and multiline strings that can be simplified in kotlin. 

You've already done other major updates like `suspend` functions, androidx migrations, and live data, so that all looks nice.

Let me know if you are open to these changes and I'll start working on things weekly/monthly

**Comment by jguerinet** [comment]
I've got some other stuff in mind for this. I do it the other way around: When building the build number is incremented and the Git tag is created as a result. Comes down to the same thing. 
For the Gradle Play Publisher, I'm using fastlane to do all of this for me.
